### ISSUE TITLE
Extract API keys definition to .env

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-express#13]
### Motivation

It is easily possible to commit API keys as a part of the pull request in `delivery.js` file. 

Currently, it is possible to [configure the project manually](https://github.com/Kentico/cloud-sample-app-express#setup)

When you configure your project manually it is required to temporarily change the source code in `delivery.js` file and that could lead to committing this unintended change that was used for, let's say testing purposes.

### Proposed solution

If the project ID was loaded from the environment, as an environment variable, it would eliminate the possibility for unintended commit to delivery.js.
Loading environment variables is possible utins [dotenv](https://www.npmjs.com/package/dotenv) library.

Best practice nowadays is to use environment variables stored in .env file.

* Set up .gitignore to ignore .env file
* Configure `delivery.js` to use .env definition for key (projectId )
* Update Readme

### Additional context

* Highly used is dotenv library: https://www.npmjs.com/package/dotenv
* Related to
    * https://github.com/Kentico/cloud-sample-app-vue/issues/23
    *  https://github.com/Kentico/cloud-sample-app-react/issues/134

**Comment by kentico-ericd** [comment]
Implemented in https://github.com/Kentico/cloud-sample-app-express/commit/4bbf487281c789bd43510bc445e0ede48004329d
